export const END_POINTS = {
  BLOG_LISTING: '/blog/blog-listing/page/1',
  BLOG_TAGS: '/tag',
  BLOG_SEARCH: '/blog/search',
  BLOG_DELETE: '/blog/bulk-delete',
  BLOG_DELETE_SINGLE: '/blog',
  DUPLICATE_POST: '/blog/duplicate',
  STATUS_COUNTS: '/blog/status-counts',
  BLOG_CREATE: '/blog',
  TAGS: '/tag',
  CATEGORIES: '/category',
  ADD_CATEGORY: '/category',
  UPDATE_CATEGORY: '/category',
  DELETE_CATEGORY: '/category',
  DELETE_MULTIPLE_CATEGORIES: '/category/bulk-delete',
  COMMENTS: '/comment/filtered',
  COMMENTS_DELETE: '/comment/bulk-delete',
}