export const PATH_NAME = {
  ROOT: '/',
  BLOG_ALL_POSTS: '/blog/all-posts',
  BLOG_NEW_POSTS: '/blog/new-posts',
  BLOG_CATEGORY: '/blog/category',
  BLOG_TAG: '/blog/tags',
  COMPARE_VEHICLES: '/compare-vehicle',
  ADD_VEHICLE: '/vehicle-add',
  COMMENTS: '/comments',
  MAKES: '/make',
  LOCATION: '/location',
  USER_MANAGEMENT_USERS_LIST: '/user-management/users-list',
  USER_MANANAEMENT_USER_ROLES: '/user-management/user-roles',
  PROFILE_SETTINGS: '/profile-settings',
  CHAT: '/chat',
  EMAIL: '/email',
  FILE_MANAGER: '/file-manager',
}