import "@mantine/core/styles.css";
import '@mantine/dates/styles.css';
import '@mantine/core/styles.layer.css';
import 'mantine-datatable/styles.layer.css';
import '@mantine/tiptap/styles.css';
import { theme } from '@/theme';
import {
  MantineProvider,
  ColorSchemeScript
} from '@mantine/core';
import {
  emotionTransform,
  MantineEmotionProvider,
} from '@mantine/emotion';
import StoreProvider from '@/store/StoreProvider';

export const metadata = {
  title: "Auto Wheel | Admin",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <ColorSchemeScript />
      </head>
      <body>
        <StoreProvider>
          <MantineProvider theme={theme} stylesTransform={emotionTransform}>
            <MantineEmotionProvider>
              {children}
            </MantineEmotionProvider>
          </MantineProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
